AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Wix Engineering Meetup | Cloud-based E2E Platform
Resources:
  wixsledmeetup:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: Wix Engineering Meetup | Cloud-based E2E Platform
      MemorySize: 1280
      Timeout: 60
      Role: >-
        <any role>
      Layers:
        - '<upload chrome-aws-lambda.zip as layer>'
